# docker-compose.yml
version: "3"
services:
  server:
    build: server
    depends_on:
      - postgres
    ports:
      - "3005:3005"

  postgres:
    image: postgres:10.4
    restart: always
    ports:
      - "35432:5432"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: astronomy