create table users(id serial,username text,birth_day integer,birth_month integer,birth_year integer,birth_minute integer,birth_hour integer);
create table signs(id serial,sign_name text,symbol text,strengths text,weaknesses text,element text,ruler text,jewelry text,yinyang boolean);
create table compatibility(id serial,signId integer,compatibleSignId integer,compatible boolean);
create table numbers(id serial,signId integer,number integer,compatible boolean);
create table colors(id serial,signId integer,color text,compatible boolean);
create table flowers(id serial,signId integer,flower text,compatible boolean);
create table directions(id serial,signId integer,direction integer,compatible boolean);
insert into signs(sign_name,symbol,strengths,weaknesses,element,ruler,jewelry,yinyang) values('Aries','Ram','hopeful, active, energetic, honest, versatile, brave, adventurous, passionate, generous, cheerful, argumentative, curious','impulsive, naive, self-willed, belligerent, impatient','Fire','Mars','Ruby',false);
insert into compatibility(signId,compatibleSignId,compatible) values(1,6,true);
insert into compatibility(signId,compatibleSignId,compatible) values(1,9,true);
insert into compatibility(signId,compatibleSignId,compatible) values(1,5,true);
insert into compatibility(signId,compatibleSignId,compatible) values(1,10,false);
insert into compatibility(signId,compatibleSignId,compatible) values(1,4,false);
insert into compatibility(signId,compatibleSignId,compatible) values(1,7,false);
insert into numbers(signId,number,compatible) values(1,1,true);
insert into numbers(signId,number,compatible) values(1,7,true);
insert into numbers(signId,number,compatible) values(1,6,true);
insert into numbers(signId,number,compatible) values(1,9,false);
insert into numbers(signId,number,compatible) values(1,8,false);
insert into numbers(signId,number,compatible) values(1,3,false);
insert into colors(signId,color,compatible) values(1,'Gold',true);
insert into colors(signId,color,compatible) values(1,'Silver',true);
insert into colors(signId,color,compatible) values(1,'Hoary',true);
insert into colors(signId,color,compatible) values(1,'Red',false);
insert into colors(signId,color,compatible) values(1,'Green',false);
insert into colors(signId,color,compatible) values(1,'Purple',false);
insert into colors(signId,color,compatible) values(1,'Black',false);
insert into flowers(signId,flower,compatible) values(1,'Bleeding Heart Vine',true);
insert into flowers(signId,flower,compatible) values(1,'Larkspur',true);
insert into flowers(signId,flower,compatible) values(1,'Hyacinth',true);
insert into directions(signId,direction,compatible) values(1,0,true);
insert into directions(signId,direction,compatible) values(1,6,true);
insert into directions(signId,direction,compatible) values(1,7,true);
insert into directions(signId,direction,compatible) values(1,3,false);
insert into signs(sign_name,symbol,strengths,weaknesses,element,ruler,jewelry,yinyang) values('Taurus','Bull','romantic, decisive, logical, diligent, ardent, patient, talented in art, perseverant, benevolent','prejudiced, dependent, stubborn','Earth','Venus','Emerald, Jade',false);
insert into compatibility(signId,compatibleSignId,compatible) values(2,1,true);
insert into compatibility(signId,compatibleSignId,compatible) values(2,6,true);
insert into compatibility(signId,compatibleSignId,compatible) values(2,11,false);
insert into compatibility(signId,compatibleSignId,compatible) values(2,12,false);
insert into compatibility(signId,compatibleSignId,compatible) values(2,2,false);
insert into compatibility(signId,compatibleSignId,compatible) values(2,4,false);
insert into compatibility(signId,compatibleSignId,compatible) values(2,8,false);
insert into numbers(signId,number,compatible) values(2,2,true);
insert into numbers(signId,number,compatible) values(2,8,true);
insert into numbers(signId,number,compatible) values(2,9,true);
insert into numbers(signId,number,compatible) values(2,1,false);
insert into numbers(signId,number,compatible) values(2,6,false);
insert into numbers(signId,number,compatible) values(2,7,false);
insert into colors(signId,color,compatible) values(2,'Red',true);
insert into colors(signId,color,compatible) values(2,'Light Yellow',true);
insert into colors(signId,color,compatible) values(2,'Black',true);
insert into colors(signId,color,compatible) values(2,'White',false);
insert into colors(signId,color,compatible) values(2,'Gold',false);
insert into colors(signId,color,compatible) values(2,'Brown',false);
insert into flowers(signId,flower,compatible) values(2,'Orchid',true);
insert into flowers(signId,flower,compatible) values(2,'Cactus',true);
insert into directions(signId,direction,compatible) values(2,1,true);
insert into directions(signId,direction,compatible) values(2,4,true);
insert into directions(signId,direction,compatible) values(2,5,true);
insert into directions(signId,direction,compatible) values(2,7,false);
insert into signs(sign_name,symbol,strengths,weaknesses,element,ruler,jewelry,yinyang) values('Gemini','Twins','multifarious, perspicacious, smart, cheerful, quick-witted, clement, charming','fickle, gossipy, amphibian','Air','Mercury','Opal',false);
insert into compatibility(signId,compatibleSignId,compatible) values(3,11,true);
insert into compatibility(signId,compatibleSignId,compatible) values(3,4,true);
insert into compatibility(signId,compatibleSignId,compatible) values(3,12,true);
insert into compatibility(signId,compatibleSignId,compatible) values(3,1,true);
insert into compatibility(signId,compatibleSignId,compatible) values(3,7,true);
insert into compatibility(signId,compatibleSignId,compatible) values(3,5,true);
insert into compatibility(signId,compatibleSignId,compatible) values(3,8,true);
insert into compatibility(signId,compatibleSignId,compatible) values(3,2,true);
insert into compatibility(signId,compatibleSignId,compatible) values(3,9,false);
insert into compatibility(signId,compatibleSignId,compatible) values(3,10,false);
insert into compatibility(signId,compatibleSignId,compatible) values(3,6,false);
insert into compatibility(signId,compatibleSignId,compatible) values(3,3,false);
insert into numbers(signId,number,compatible) values(3,2,true);
insert into numbers(signId,number,compatible) values(3,3,true);
insert into numbers(signId,number,compatible) values(3,7,true);
insert into numbers(signId,number,compatible) values(3,1,false);
insert into numbers(signId,number,compatible) values(3,5,false);
insert into numbers(signId,number,compatible) values(3,6,false);
insert into colors(signId,color,compatible) values(3,'Brown',true);
insert into colors(signId,color,compatible) values(3,'Yellow',true);
insert into colors(signId,color,compatible) values(3,'Purple',true);
insert into colors(signId,color,compatible) values(3,'Blue',false);
insert into colors(signId,color,compatible) values(3,'White',false);
insert into colors(signId,color,compatible) values(3,'Gold',false);
insert into flowers(signId,flower,compatible) values(3,'Calla Lily',true);
insert into flowers(signId,flower,compatible) values(3,'Jasmine',true);
insert into flowers(signId,flower,compatible) values(3,'Marigold',true);
insert into directions(signId,direction,compatible) values(3,1,true);
insert into directions(signId,direction,compatible) values(3,5,true);
insert into directions(signId,direction,compatible) values(3,7,true);
insert into directions(signId,direction,compatible) values(3,3,false);
insert into signs(sign_name,symbol,strengths,weaknesses,element,ruler,jewelry,yinyang) values('Cancer','Crab','with strong sixth sense, subjective, gentle, swift, imaginative, careful, dedicated, perseverant, kind, caring','greedy, possessive, sensitive, prim','Water','Moon','Pearl',false);
insert into compatibility(signId,compatibleSignId,compatible) values(4,3,true);
insert into compatibility(signId,compatibleSignId,compatible) values(4,12,true);
insert into compatibility(signId,compatibleSignId,compatible) values(4,8,true);
insert into compatibility(signId,compatibleSignId,compatible) values(4,10,false);
insert into compatibility(signId,compatibleSignId,compatible) values(4,11,false);
insert into compatibility(signId,compatibleSignId,compatible) values(4,7,false);
insert into numbers(signId,number,compatible) values(4,3,true);
insert into numbers(signId,number,compatible) values(4,4,true);
insert into numbers(signId,number,compatible) values(4,9,true);
insert into numbers(signId,number,compatible) values(4,6,false);
insert into numbers(signId,number,compatible) values(4,7,false);
insert into numbers(signId,number,compatible) values(4,8,false);
insert into colors(signId,color,compatible) values(4,'Green',true);
insert into colors(signId,color,compatible) values(4,'Red',true);
insert into colors(signId,color,compatible) values(4,'Purple',true);
insert into colors(signId,color,compatible) values(4,'Gold',false);
insert into colors(signId,color,compatible) values(4,'Brown',false);
insert into colors(signId,color,compatible) values(4,'Black',false);
insert into flowers(signId,flower,compatible) values(4,'Carnation',true);
insert into flowers(signId,flower,compatible) values(4,'Primrose',true);
insert into flowers(signId,flower,compatible) values(4,'Alice Flower',true);
insert into directions(signId,direction,compatible) values(4,2,true);
insert into directions(signId,direction,compatible) values(4,3,true);
insert into directions(signId,direction,compatible) values(4,4,true);
insert into directions(signId,direction,compatible) values(4,6,false);
insert into signs(sign_name,symbol,strengths,weaknesses,element,ruler,jewelry,yinyang) values('Leo','Lion','proud, charitable, reflective, loyal and enthusiastic','arrogant, vainglorious, indulgent, wasteful, willful, and self-complacent','Fire','Sun','Gold',false);
insert into compatibility(signId,compatibleSignId,compatible) values(5,10,true);
insert into compatibility(signId,compatibleSignId,compatible) values(5,12,true);
insert into compatibility(signId,compatibleSignId,compatible) values(5,11,false);
insert into compatibility(signId,compatibleSignId,compatible) values(5,8,false);
insert into numbers(signId,number,compatible) values(5,1,true);
insert into numbers(signId,number,compatible) values(5,7,true);
insert into numbers(signId,number,compatible) values(5,8,true);
insert into numbers(signId,number,compatible) values(5,2,false);
insert into numbers(signId,number,compatible) values(5,5,false);
insert into numbers(signId,number,compatible) values(5,9,false);
insert into colors(signId,color,compatible) values(5,'White',true);
insert into colors(signId,color,compatible) values(5,'Gold',true);
insert into colors(signId,color,compatible) values(5,'Blue',true);
insert into colors(signId,color,compatible) values(5,'Red',false);
insert into colors(signId,color,compatible) values(5,'Black',false);
insert into colors(signId,color,compatible) values(5,'Grey',false);
insert into colors(signId,color,compatible) values(5,'Dark Coffee',false);
insert into flowers(signId,flower,compatible) values(5,'Chrysanthemum',true);
insert into flowers(signId,flower,compatible) values(5,'Alliums',true);
insert into directions(signId,direction,compatible) values(5,0,true);
insert into directions(signId,direction,compatible) values(5,6,true);
insert into directions(signId,direction,compatible) values(5,7,true);
insert into directions(signId,direction,compatible) values(5,2,false);
insert into signs(sign_name,symbol,strengths,weaknesses,element,ruler,jewelry,yinyang) values('Virgo','Virgin Maiden','helping, elegant, perfectionist, modest, practical, clearheaded','picky, nosey, tortuous, confining','Earth','Mercury','Sapphire, Amber',false);
insert into compatibility(signId,compatibleSignId,compatible) values(6,10,true);
insert into compatibility(signId,compatibleSignId,compatible) values(6,2,true);
insert into compatibility(signId,compatibleSignId,compatible) values(6,9,false);
insert into compatibility(signId,compatibleSignId,compatible) values(6,12,false);
insert into compatibility(signId,compatibleSignId,compatible) values(6,3,false);
insert into compatibility(signId,compatibleSignId,compatible) values(6,6,false);
insert into compatibility(signId,compatibleSignId,compatible) values(6,7,false);
insert into numbers(signId,number,compatible) values(6,5,true);
insert into numbers(signId,number,compatible) values(6,7,true);
insert into numbers(signId,number,compatible) values(6,8,true);
insert into numbers(signId,number,compatible) values(6,1,false);
insert into numbers(signId,number,compatible) values(6,3,false);
insert into numbers(signId,number,compatible) values(6,9,false);
insert into colors(signId,color,compatible) values(6,'Gold',true);
insert into colors(signId,color,compatible) values(6,'Brown',true);
insert into colors(signId,color,compatible) values(6,'Yellow',true);
insert into colors(signId,color,compatible) values(6,'White',false);
insert into colors(signId,color,compatible) values(6,'Green',false);
insert into flowers(signId,flower,compatible) values(6,'Gladiola',true);
insert into flowers(signId,flower,compatible) values(6,'Impatiens',true);
insert into flowers(signId,flower,compatible) values(6,'Cockscomb',true);
insert into directions(signId,direction,compatible) values(6,1,true);
insert into directions(signId,direction,compatible) values(6,5,true);
insert into directions(signId,direction,compatible) values(6,6,true);
insert into directions(signId,direction,compatible) values(6,0,false);
insert into directions(signId,direction,compatible) values(6,2,false);
insert into signs(sign_name,symbol,strengths,weaknesses,element,ruler,jewelry,yinyang) values('Libra','Scales','idealistic, equitable, just, strong social skills, aesthetic, charming, artistic, beautiful, kind-hearted','hesitant, narcissistic, lazy, perfunctory, freewheeling','Air','Venus','Coral, Amber',false);
insert into compatibility(signId,compatibleSignId,compatible) values(7,12,true);
insert into compatibility(signId,compatibleSignId,compatible) values(7,1,false);
insert into compatibility(signId,compatibleSignId,compatible) values(7,4,false);
insert into compatibility(signId,compatibleSignId,compatible) values(7,6,false);
insert into numbers(signId,number,compatible) values(7,3,true);
insert into numbers(signId,number,compatible) values(7,4,true);
insert into numbers(signId,number,compatible) values(7,9,true);
insert into numbers(signId,number,compatible) values(7,1,false);
insert into numbers(signId,number,compatible) values(7,6,false);
insert into numbers(signId,number,compatible) values(7,7,false);
insert into colors(signId,color,compatible) values(7,'Green',true);
insert into colors(signId,color,compatible) values(7,'Red',true);
insert into colors(signId,color,compatible) values(7,'Purple',true);
insert into flowers(signId,flower,compatible) values(7,'Rose',true);
insert into flowers(signId,flower,compatible) values(7,'Oncidium',true);
insert into flowers(signId,flower,compatible) values(7,'Cymbidium Orchids',true);
insert into directions(signId,direction,compatible) values(7,2,true);
insert into directions(signId,direction,compatible) values(7,3,true);
insert into directions(signId,direction,compatible) values(7,4,true);
insert into directions(signId,direction,compatible) values(7,0,false);
insert into directions(signId,direction,compatible) values(7,6,false);
insert into signs(sign_name,symbol,strengths,weaknesses,element,ruler,jewelry,yinyang) values('Scorpio','Scorpion','mysterious, rational, intelligent, independent, intuitive, dedicated, insightful, charming, sensible','suspicious, fanatical, complicated, possessive, arrogant, self-willed, extreme','Water','Pluto, Mars','Jasper, Black Crystal',false);
insert into compatibility(signId,compatibleSignId,compatible) values(8,11,true);
insert into compatibility(signId,compatibleSignId,compatible) values(8,12,true);
insert into compatibility(signId,compatibleSignId,compatible) values(8,4,true);
insert into compatibility(signId,compatibleSignId,compatible) values(8,2,false);
insert into compatibility(signId,compatibleSignId,compatible) values(8,5,false);
insert into numbers(signId,number,compatible) values(8,2,true);
insert into numbers(signId,number,compatible) values(8,5,true);
insert into numbers(signId,number,compatible) values(8,8,true);
insert into numbers(signId,number,compatible) values(8,1,false);
insert into numbers(signId,number,compatible) values(8,3,false);
insert into numbers(signId,number,compatible) values(8,9,false);
insert into colors(signId,color,compatible) values(8,'Yellow',true);
insert into colors(signId,color,compatible) values(8,'Gray',true);
insert into colors(signId,color,compatible) values(8,'Brown',true);
insert into colors(signId,color,compatible) values(8,'Gold',true);
insert into colors(signId,color,compatible) values(8,'Red',false);
insert into colors(signId,color,compatible) values(8,'Blue',false);
insert into colors(signId,color,compatible) values(8,'Green',false);
insert into flowers(signId,flower,compatible) values(8,'Hydrangea',true);
insert into flowers(signId,flower,compatible) values(8,'Pitcher Plant',true);
insert into flowers(signId,flower,compatible) values(8,'Marguerite',true);
insert into directions(signId,direction,compatible) values(8,1,true);
insert into directions(signId,direction,compatible) values(8,3,true);
insert into directions(signId,direction,compatible) values(8,2,false);
insert into directions(signId,direction,compatible) values(8,6,false);
insert into signs(sign_name,symbol,strengths,weaknesses,element,ruler,jewelry,yinyang) values('Sagittarius','Archer','insightful, superior, rational, brave, beautiful, lively, lovely, optimistic','forgetful, careless, rash','Fire','Jupiter','Amethyst',false);
insert into compatibility(signId,compatibleSignId,compatible) values(9,10,true);
insert into compatibility(signId,compatibleSignId,compatible) values(9,1,true);
insert into compatibility(signId,compatibleSignId,compatible) values(9,5,true);
insert into compatibility(signId,compatibleSignId,compatible) values(9,3,false);
insert into compatibility(signId,compatibleSignId,compatible) values(9,6,false);
insert into numbers(signId,number,compatible) values(9,2,true);
insert into numbers(signId,number,compatible) values(9,3,true);
insert into numbers(signId,number,compatible) values(9,5,false);
insert into numbers(signId,number,compatible) values(9,9,false);
insert into colors(signId,color,compatible) values(9,'Gold',true);
insert into colors(signId,color,compatible) values(9,'Blue',true);
insert into colors(signId,color,compatible) values(9,'Green',true);
insert into colors(signId,color,compatible) values(9,'Yellow',false);
insert into colors(signId,color,compatible) values(9,'Brown',false);
insert into flowers(signId,flower,compatible) values(9,'Lily',true);
insert into flowers(signId,flower,compatible) values(9,'African Violet',true);
insert into directions(signId,direction,compatible) values(9,1,true);
insert into directions(signId,direction,compatible) values(9,3,true);
insert into directions(signId,direction,compatible) values(9,6,false);
insert into signs(sign_name,symbol,strengths,weaknesses,element,ruler,jewelry,yinyang) values('Capricorn','Goat','excellent, intelligent, practical, reliable, perseverant, generous, optimistic, cute, persistent','stubborn, lonely, and suspicious','Earth','Saturn','Black Jade',false);
insert into compatibility(signId,compatibleSignId,compatible) values(10,9,true);
insert into compatibility(signId,compatibleSignId,compatible) values(10,2,true);
insert into compatibility(signId,compatibleSignId,compatible) values(10,6,true);
insert into compatibility(signId,compatibleSignId,compatible) values(10,11,false);
insert into compatibility(signId,compatibleSignId,compatible) values(10,1,false);
insert into compatibility(signId,compatibleSignId,compatible) values(10,3,false);
insert into compatibility(signId,compatibleSignId,compatible) values(10,4,false);
insert into numbers(signId,number,compatible) values(10,1,true);
insert into numbers(signId,number,compatible) values(10,9,true);
insert into numbers(signId,number,compatible) values(10,3,false);
insert into numbers(signId,number,compatible) values(10,4,false);
insert into colors(signId,color,compatible) values(10,'Red',true);
insert into colors(signId,color,compatible) values(10,'Blue',true);
insert into colors(signId,color,compatible) values(10,'Purple',true);
insert into colors(signId,color,compatible) values(10,'White',false);
insert into colors(signId,color,compatible) values(10,'Green',false);
insert into flowers(signId,flower,compatible) values(10,'Tulip',true);
insert into flowers(signId,flower,compatible) values(10,'Evergreen',true);
insert into flowers(signId,flower,compatible) values(10,'Peach Blossom',true);
insert into directions(signId,direction,compatible) values(10,0,true);
insert into directions(signId,direction,compatible) values(10,3,true);
insert into directions(signId,direction,compatible) values(10,4,true);
insert into directions(signId,direction,compatible) values(10,7,false);
insert into signs(sign_name,symbol,strengths,weaknesses,element,ruler,jewelry,yinyang) values('Aquarius','Water carrier','original, tolerant, ideal, calm, friendly, charitable, independent, smart, practical','changeful, disobedient, liberalistic, hasty, rebel','Air','Uranus','Black Pearl',false);
insert into compatibility(signId,compatibleSignId,compatible) values(11,1,true);
insert into compatibility(signId,compatibleSignId,compatible) values(11,3,true);
insert into compatibility(signId,compatibleSignId,compatible) values(11,8,true);
insert into compatibility(signId,compatibleSignId,compatible) values(11,10,false);
insert into compatibility(signId,compatibleSignId,compatible) values(11,11,false);
insert into compatibility(signId,compatibleSignId,compatible) values(11,2,false);
insert into compatibility(signId,compatibleSignId,compatible) values(11,5,false);
insert into numbers(signId,number,compatible) values(11,1,true);
insert into numbers(signId,number,compatible) values(11,3,true);
insert into numbers(signId,number,compatible) values(11,4,true);
insert into numbers(signId,number,compatible) values(11,6,false);
insert into numbers(signId,number,compatible) values(11,7,false);
insert into numbers(signId,number,compatible) values(11,8,false);
insert into colors(signId,color,compatible) values(11,'Gray',true);
insert into colors(signId,color,compatible) values(11,'Blue',true);
insert into colors(signId,color,compatible) values(11,'White',true);
insert into colors(signId,color,compatible) values(11,'Orange',true);
insert into colors(signId,color,compatible) values(11,'Gold',false);
insert into colors(signId,color,compatible) values(11,'Silver',false);
insert into colors(signId,color,compatible) values(11,'Brown',false);
insert into colors(signId,color,compatible) values(11,'Black',false);
insert into flowers(signId,flower,compatible) values(11,'Cineraria',true);
insert into flowers(signId,flower,compatible) values(11,'Anthurium',true);
insert into directions(signId,direction,compatible) values(11,2,true);
insert into directions(signId,direction,compatible) values(11,3,true);
insert into directions(signId,direction,compatible) values(11,4,true);
insert into directions(signId,direction,compatible) values(11,7,false);
insert into signs(sign_name,symbol,strengths,weaknesses,element,ruler,jewelry,yinyang) values('Pisces','Fish','conscious, aesthetic, platonic, dedicated, kind, with good temper','recessive, sentimental, indecisive, unrealistic','Water','Neptune','Ivory Stone',false);
insert into compatibility(signId,compatibleSignId,compatible) values(12,4,true);
insert into compatibility(signId,compatibleSignId,compatible) values(12,5,true);
insert into compatibility(signId,compatibleSignId,compatible) values(12,7,true);
insert into compatibility(signId,compatibleSignId,compatible) values(12,8,true);
insert into compatibility(signId,compatibleSignId,compatible) values(12,2,false);
insert into compatibility(signId,compatibleSignId,compatible) values(12,6,false);
insert into numbers(signId,number,compatible) values(12,3,true);
insert into numbers(signId,number,compatible) values(12,4,true);
insert into numbers(signId,number,compatible) values(12,9,true);
insert into numbers(signId,number,compatible) values(12,1,false);
insert into numbers(signId,number,compatible) values(12,7,false);
insert into numbers(signId,number,compatible) values(12,8,false);
insert into colors(signId,color,compatible) values(12,'Red',true);
insert into colors(signId,color,compatible) values(12,'Blue',true);
insert into colors(signId,color,compatible) values(12,'Pink',true);
insert into colors(signId,color,compatible) values(12,'Purple',true);
insert into colors(signId,color,compatible) values(12,'White',false);
insert into colors(signId,color,compatible) values(12,'Dark Yellow',false);
insert into colors(signId,color,compatible) values(12,'Dark Brown',false);
insert into flowers(signId,flower,compatible) values(12,'Snapdragon',true);
insert into flowers(signId,flower,compatible) values(12,'Plantain Lily',true);
insert into flowers(signId,flower,compatible) values(12,'Nerve Plant',true);
insert into directions(signId,direction,compatible) values(12,2,true);
insert into directions(signId,direction,compatible) values(12,3,true);
insert into directions(signId,direction,compatible) values(12,4,true);
insert into directions(signId,direction,compatible) values(12,7,false);